export const SCORING_CONFIG = {
    RULES: {
        AUTHORITY_POINTS: 20,
        OTP_POINTS: 25,
        CREDENTIAL_POINTS: 20,
        PAYMENT_POINTS: 20,
        URGENCY_POINTS: 10,
        KNOWN_SCAM_POINTS: 20,
        ESCALATION_POINTS: 8,
    },
    SEMANTIC_BONUS_MULTIPLIER: 15,
    THRESHOLDS: {
        MEDIUM: 0.34,
        HIGH: 0.60,
        CRITICAL: 0.80,
        LOCKDOWN: 0.95
    },
    PAYMENT_WARNING_THRESHOLD: 20,
    PAYMENT_CONFIRM_THRESHOLD: 50,
    PAYMENT_STRONG_CONFIRM_THRESHOLD: 70,
    PAYMENT_BLOCK_THRESHOLD: 90
};
