/**
 * InferenceOrchestrator
 *
 * Single abstraction layer for all LLM inference in KavachAI.
 * The rest of the application communicates exclusively with this orchestrator —
 * it never directly instantiates VertexProvider or LocalSemanticProvider.
 *
 * Provider hierarchy:
 *   1. VertexProvider  (Gemini 2.5 Flash via Vertex AI)
 *   2. LocalSemanticProvider  (deterministic keyword-fallback)
 *
 * Fallback policy:
 *   - If Vertex is unavailable at init or throws a non-auth error at runtime,
 *     the orchestrator transparently falls back to LocalSemanticProvider.
 *   - Authentication / permission errors are logged clearly but do not crash the server.
 *   - Fallback count is tracked for observability.
 *
 * Future migration note:
 *   To switch the inference SDK (e.g. @google/genai), only replace
 *   VertexProvider.js. InferenceOrchestrator and all callers remain untouched.
 */

import { VertexProvider, AuthenticationError, PermissionError, ModelUnavailableError } from './VertexProvider.js';
import { LocalSemanticProvider } from './LocalSemanticProvider.js';

// ─── Non-retryable errors that must NOT trigger a local fallback silently ────
// (auth / permission issues should surface clearly, not be hidden by fallback)
const HARD_ERRORS = [AuthenticationError, PermissionError];

function isHardError(err) {
    return HARD_ERRORS.some(cls => err instanceof cls);
}

class InferenceOrchestrator {
    constructor() {
        this._vertexProvider   = null;
        this._localProvider    = new LocalSemanticProvider();
        this._fallbackActive   = false;
        this._fallbackCount    = 0;
        this._fallbackReason   = null;
        this._initialized      = false;
    }

    /**
     * Asynchronous initialization — called once on server startup.
     * Attempts to bring up VertexProvider; on failure records reason and
     * sets fallback mode but does NOT throw.
     */
    async initialize() {
        if (this._initialized) return;

        try {
            this._vertexProvider = new VertexProvider();
            if (!this._vertexProvider.initialized) {
                // Constructor logged the error; promote it here.
                this._fallbackActive = true;
                this._fallbackReason = this._vertexProvider.initError?.message ?? 'SDK failed to initialize';
                console.warn(`[InferenceOrchestrator] Vertex init failed — falling back to Local Semantic Engine. Reason: ${this._fallbackReason}`);
            } else {
                console.log(`[InferenceOrchestrator] Vertex AI active — model=${this._vertexProvider.modelName}`);
            }
        } catch (err) {
            this._fallbackActive = true;
            this._fallbackReason = err.message;
            console.error(`[InferenceOrchestrator] Unexpected error during Vertex init — ${err.message}. Falling back to Local Semantic Engine.`);
        }

        this._initialized = true;
    }

    /**
     * Run inference on a pre-built prompt string.
     * Attempts Vertex first; falls back to LocalSemantic only on non-hard errors.
     *
     * @param {string} promptText  - The full prompt as generated by analyzePrompt.js
     * @param {string} chunkText   - Raw transcript chunk (used by LocalSemantic fallback)
     * @param {string} [reqId]     - Optional request ID for structured logging
     * @returns {Promise<object>}  - Normalised analysis result
     */
    async analyze(promptText, chunkText, reqId = 'N/A') {
        await this.initialize(); // idempotent

        if (!this._fallbackActive && this._vertexProvider?.initialized) {
            try {
                const result = await this._vertexProvider.analyzeChunk(promptText);
                return result;
            } catch (err) {
                if (isHardError(err)) {
                    // Hard errors are serious — log prominently and switch to fallback
                    // to keep the server alive, but warn loudly.
                    console.error(
                        `[InferenceOrchestrator][REQ-${reqId}] Hard error from Vertex AI (${err.name}): ${err.message}. Enabling permanent fallback.`
                    );
                    this._fallbackActive = true;
                    this._fallbackReason = `${err.name}: ${err.message}`;
                } else {
                    // Transient / quota / model error — log and use local for this request only
                    console.warn(
                        `[InferenceOrchestrator][REQ-${reqId}] Vertex AI inference failed (${err.name}): ${err.message}. Using Local Semantic Engine for this request.`
                    );
                }
                this._fallbackCount++;
            }
        }

        // Local Semantic fallback
        console.log(`[InferenceOrchestrator][REQ-${reqId}] Local Semantic Engine active (fallbackCount=${this._fallbackCount}).`);
        return this._localProvider.runFallback(chunkText);
    }

    /**
     * Health summary for the /health/vertex endpoint.
     * @returns {object}
     */
    health() {
        const vertexHealth = this._vertexProvider?.checkHealth?.() ?? null;
        return {
            inferenceProvider:  this._fallbackActive ? 'LocalSemanticProvider' : 'VertexProvider',
            inferenceModel:     this._fallbackActive ? 'local-semantic-engine' : (this._vertexProvider?.modelName ?? 'unknown'),
            fallbackEnabled:    true,   // always true — graceful degradation is always on
            fallbackActive:     this._fallbackActive,
            fallbackCount:      this._fallbackCount,
            fallbackReason:     this._fallbackReason,
            vertexInitialized:  this._vertexProvider?.initialized ?? false,
            project:            this._vertexProvider?.project ?? process.env.GOOGLE_CLOUD_PROJECT ?? 'unknown',
            region:             this._vertexProvider?.location ?? process.env.GOOGLE_CLOUD_LOCATION ?? 'unknown',
        };
    }
}

// Singleton — shared across all route handlers
export const inferenceOrchestrator = new InferenceOrchestrator();
